config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :quests, only: [:index, :show, :create, :update, :destroy]
  resources :boards, only: [:show, :create] 
  resources :users, only: [:show, :create, :destroy]
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "boards#index"
end

app/models/quest.rb
class Quest < ApplicationRecord
    belongs_to :board
    belongs_to :author, class_name: "User"

    has_many :tasks, dependent: :destroy

    validates :title, presence: true
    validates :description, presence: true
    validates :visibility, inclusion: { in: ["personal", "public", "targeted"] }
    validates :repeat, inclusion: { in: ["never", "daily", "weekly", "monthly"] }

    def completed?
        tasks.all?(&:completed)
    end

    def visibility?
        visibility
    end

    def repeat?
        repeat
    end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: %i[ show edit update destroy ]

  # GET /quests or /quests.json
  def index
    @quests = Quest.all
  end

  # GET /quests/1 or /quests/1.json
  def show
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests or /quests.json
  def create
    @quest = Quest.new(quest_params)

    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: "Quest was successfully created." }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1 or /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: "Quest was successfully updated." }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1 or /quests/1.json
  def destroy
    @quest.destroy!

    respond_to do |format|
      format.html { redirect_to quests_path, status: :see_other, notice: "Quest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def quest_params
      params.expect(quest: [ :title, :description, :completed, :author ])
    end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_with(model: quest) do |form| %>
  <% if quest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
        <% quest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.checkbox :completed %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quests/_quest.html.erb
<div id="<%= dom_id quest %>">
  <p>
    <strong>Title:</strong>
    <%= quest.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= quest.description %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= quest.completed %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= quest.author %>
  </p>

</div>

app/views/quests/edit.html.erb
<% content_for :title, "Editing quest" %>

<h1>Editing quest</h1>

<%= render "form", quest: @quest %>

<br>

<div>
  <%= link_to "Show this quest", @quest %> |
  <%= link_to "Back to quests", quests_path %>
</div>

app/views/quests/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Quests" %>

<h1>Quests</h1>

<div id="quests">
  <% @quests.each do |quest| %>
    <%= render quest %>
    <p>
      <%= link_to "Show this quest", quest %>
    </p>
  <% end %>
</div>

<%= link_to "New quest", new_quest_path %>

app/views/quests/new.html.erb
<% content_for :title, "New quest" %>

<h1>New quest</h1>

<%= render "form", quest: @quest %>

<br>

<div>
  <%= link_to "Back to quests", quests_path %>
</div>

app/views/quests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quest %>

<div>
  <%= link_to "Edit this quest", edit_quest_path(@quest) %> |
  <%= link_to "Back to quests", quests_path %>

  <%= button_to "Destroy this quest", @quest, method: :delete %>
</div>